### ISSUE TITLE
widnows10环境中sbox命令出错

### ISSUE THREAD

**Issue by xuemind** [aliyun/fcli#13]
参考[官方的快速入门应用示例2](https://help.aliyun.com/document_detail/52586.html?spm=5176.doc53097.6.550.XnZ3QR)
执行到sbox的时候出错了

```
Welcome to the function compute world. Have fun!
>>> sbox -d code -t nodejs4.4
Entering the container. Your code is in the /code direcotry.
Error: exec: "sh": executable file not found in %PATH%
>>>
```

环境：windows 10 Pro, Docker 17.06.0-ce-win19, fcli-v0.6-win-386

**Comment by jaczhao** [comment]
跟进中

**Comment by MillerRen** [comment]
遇到同样问题，linux下， 0.9. docker not found

**Comment by hryang** [comment]
您好，0.10版本已经解决了sbox在windows下使用的问题。
