### ISSUE TITLE
登录失败后怎么重新配置登录信息

### ISSUE THREAD

**Issue by SocketNet** [aliyun/fcli#15]
config似乎没有功能

**Comment by hryang** [comment]
您好，请问是最新版本的fcli吗？请说明一下重现步骤。

**Comment by SocketNet** [comment]
是最新版本的，系统是Deepin，执行第一次需要输入id我当时没有就关闭了。然后申请好之后发现打开shell不能配置登录信息了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Haoran Yang<mailto:notifications@github.com>
发送时间: 2017年8月9日 20:37
收件人: aliyun/fcli<mailto:fcli@noreply.github.com>
抄送: SocketNet<mailto:tanxiongwei@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [aliyun/fcli] 登录失败后怎么重新配置登录信息 (#15)


您好，请问是最新版本的fcli吗？请说明一下重现步骤。

―

**Comment by hryang** [comment]
您好，

请执行`fcli config --access_key_id=your_id`，或者在shell模式下执行`config --access_key_id=your_id` 应该都可以更新id。

**Comment by jaczhao** [comment]
可以使用fci config 配置，转到使用说明中。
