### ISSUE TITLE
windows fcli create function报错找不到code目录

### ISSUE THREAD

**Issue by wind-tangkai** [aliyun/fcli#16]
error_message: \tmp\code8b0409e1-95b6-4b40-b4e7-47fcf905a57f.zip (系统找不到指定的路径。)

**Comment by hryang** [comment]
请提供一下重现步骤。

**Comment by wind-tangkai** [comment]
抱歉，开错地方了，java sdk问题：https://github.com/aliyun/fc-java-sdk/issues/20
