### ISSUE TITLE
windows下运行几分钟后，进入一种状态，f,d等输入不了，d是删除右侧字符。

### ISSUE THREAD

**Issue by LordRobert** [aliyun/fcli#18]
windows下运行几分钟后，进入一种状态，f,d等输入不了，d是删除右侧字符。然后就用不了。

**Comment by jaczhao** [comment]
跟进中

**Comment by jaczhao** [comment]
与 lordRobert 联调，与本机程序键盘冲突，若有问题细节，继续跟进

**Comment by lkiarest** [comment]
@jaczhao 请问与那个程序冲突。。我这边也是同样的现象，试了powershell也不行
