### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by ray-z** [aliyun/fcli#19]
在做[应用式例3](https://help.aliyun.com/document_detail/52586.html?spm=5176.doc52586.6.551.ax3fBn)的时候，用`mkt`上传的时候报错，加了`-timeout`选项也没有用：
`mkf demo/resize -t nodejs6 -h image_process.resize -d code --timeout 300`

`/code`文件夹大小 16.7mb。

**Comment by ray-z** [comment]
从`华东1`换去`华东2`就可以了。是因为网速问题吗？可不可以提高`timeout`的上限？

**Comment by lfzyx** [comment]
是的，我也在华东1遇到这个问题了，只要文件夹大一点就超时

**Comment by jaczhao** [comment]
![image](https://user-images.githubusercontent.com/5118810/34238683-eb3a9140-e63d-11e7-94e1-378f53da3f3e.png)

下载最新的版本，可以配置一下timeout的时间
