### ISSUE TITLE
没有fcli命令

### ISSUE THREAD

**Issue by wirechen** [aliyun/fcli#22]
- mac环境
- 配置环境成功
- 没有fcli命令  
----
难道还要配置系统环境变量？

**Comment by jaczhao** [comment]
应该是你配置错误了，只要把你fcli的所在路径加到sys的path下就可以了，或者你直接copy /usr/local/bin/。 再者你也可以到fcli的路径下，直接./fcli进行使用。

**Comment by stone12379** [comment]
"应该是你配置错误了"，怎么配错了，错在哪里？这样的回答真是不负责任。

**Comment by vangie** [comment]
@wirechen 也可以试试 hombrew 的方式。
```
brew tap vangie/formula
brew install fcli
```
