### ISSUE TITLE
fcli不支持将endpoint, access_key, access_secret等信息作为参数传入

### ISSUE THREAD

**Issue by hilr** [aliyun/fcli#27]
应该支持所有参数都可以通过--param paramValue 的方式传入，目前fcli不能同时操作两个region的函数，如果配置文件里的参数都可以通过命令行参数传入，就可以支持同时操作多个region的函数

**Comment by e2tox** [comment]
需要实现类似 AWS_ACCESS_KEY_ID 和 AWS_SECRET_ACCESS_KEY 的方式， --param 方式传入会留下安全隐患，比如 cat ~/.bash_history

这个功能很重要，因为缺少这个功能将无法在CI节点执行自动化部署

**Comment by quick-sort** [comment]
fcli应该可以被用在bash script里，作为一个单纯没有状态的工具使用

**Comment by vangie** [comment]
> fcli应该可以被用在bash script里，作为一个单纯没有状态的工具使用

fcli 有非交互模式的，能具体说说您碰到的问题，我们好针对性的改进。

**Comment by vangie** [comment]
已经在 0.18 版本中加入了对 ALIYUN_ACCESS_KEY_ID 和 ALIYUN_ACCESS_KEY_SECRET 环境变量的支持
