### ISSUE TITLE
SignatureNotMatch

### ISSUE THREAD

**Issue by sherrycherish** [aliyun/fcli#6]
Hi, I've checked and set all of the configs, but : 
`>>> mks demo

Error: {
  "HttpStatus": 403,
  "RequestId": "...",
  "ErrorCode": "SignatureNotMatch",
  "ErrorMessage": "signature does not match"
}`

**Comment by hryang** [comment]
Could you please post your config? 

> Note: please remove the credential info.

**Comment by hryang** [comment]
先关闭issue，等提供可重现问题的信息再跟进。
